mybatis:
  mapperLocations: classpath:mapper/*.xml

kiisoo:
  kafka:
    servers: 45.32.66.42:9092
    producer:
      key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
      value-serializer-class: org.apache.kafka.common.serialization.StringSerializer
spring:
  datasource:
    url: jdbc:mysql://192.168.0.215:3306/p2p?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: p2p
    password: p2p
    driver-class-name: com.mysql.cj.jdbc.Driver

redis:
  servers: 45.32.66.42



