mybatis:
  mapperLocations: classpath:mapper/*.xml

kafka:
  servers: 173.82.105.141:9092,173.82.238.114:9092

#kiisoo:
#  kafka:
#    servers: 173.82.105.141:9092,173.82.238.114:9092
#    producer:
#      key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer-class: org.apache.kafka.common.serialization.StringSerializer
spring:
  datasource:
    url: jdbc:mysql://ip:3306/p2p?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: ci071826
    driver-class-name: com.mysql.cj.jdbc.Driver

  #如果用@RabbitListener，下面的变量名要完全对的上，而且放在spring里面
  rabbitmq:
    virtual-host: /
    username: admin
    password: rm123456
    port: 5672
    host: 39.99.247.252

redis:
  servers: 173.82.105.141:6379







